spring.application.name=sentinel-india
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:sentinel_india}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:sentinel}
spring.datasource.password=${MYSQLPASSWORD:sentinel123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}

bhuvan.token=${BHUVAN_TOKEN:}
openaq.key=${OPENAQ_KEY:3e93f308dcc4718b4f84dc94885fc50aa192f8272c201fdbd79214e3554ce9a3}
opensky.user=${OPENSKY_USER:rujul.rumale@gmail.com-api-client}
opensky.pass=${OPENSKY_PASS:aCs3CGKDmm0msm9lbxOFJbetzDUCZ38T}
n2yo.key=${N2YO_KEY:779RYE-UUWYGM-R2KKD7-5OPV}
aisstream.key=${AISSTREAM_KEY:70decd61579de3808e400c8db84836a75fe5be7c}
railapi.key=${RAILAPI_KEY:}
datagovin.key=${DATAGOVIN_KEY:}
owm.key=${OWM_KEY:bcb3bc4e4265d99fa6e1723dd83dbb1b}
